adjusted pip install package for gentoo linux
cniw/mpv-discordRPC pull request #24
Opened 2022-06-10 19:13 UTC by zoofyiscool

2022-06-10 20:10 UTC, cniw requested changes
and do change on install-osx.sh file as well

2022-06-10 20:10 UTC, cniw commented on install-linux.sh
> +    pip3 install pypresence --user
please move the --user between install and pypresence

2022-06-11 00:48 UTC, zoofyiscool commented
added in new commit to the same PR

2022-06-11 06:51 UTC, cniw approved these changes
looks good, thanks

2022-06-11 07:01 UTC, merged